# **Tugas UAS - II4013 Data Analytics**
## Kelompok 1


*  Naura Ayurachmani (18223061)
*  Catherine Alicia N. (18223069)
*  Aliya Harta A. (18223081)
*  Noeriza Aqila W. (18223095)

# Import Library

In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd

# Load Dataset

In [ ]:
# Membaca file xlsx
SIPSN = pd.read_excel('Dataset/Data_Capaian_SIPSN_KLHK_2025.xlsx', skiprows=1)
TPA = pd.read_excel('Dataset/data_sipsn.xlsx', skiprows=1)
# Membaca file geojson
MAP = gpd.read_file('Dataset/gadm41_IDN_2.json')

In [4]:
print ("Capaian SIPSN Dataframe")
SIPSN.head()

Capaian SIPSN Dataframe

,Tahun,Provinsi,Kabupaten/Kota,Timbulan Sampah Tahunan (ton/tahun)(A),Pengurangan Sampah Tahunan (ton/tahun)(B),%Pengurangan Sampah(B/A),Penanganan Sampah Tahunan (ton/tahun)(C),%Penanganan Sampah(C/A),Sampah Terkelola Tahunan (ton/tahun)(B+C),%Sampah Terkelola(B+C)/A,Daur ulang Sampah Tahunan (ton/tahun)(D),Bahan baku Sampah Tahunan (ton/tahun)(E),Recycling Rate(D+E)/A,P1/P2
0,2025,Aceh,Kab. Aceh Selatan,35331.12,0.00,0.0,18.62,0.05,18.62,0.05,0.0,18.62,0.05,P 1
1,2025,Aceh,Kab. Aceh Tenggara,42994.99,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,P 1
2,2025,Aceh,Kab. Aceh Timur,67363.09,1.88,0.0,21109.05,31.34,21110.93,31.34,0.0,861.40,1.28,P 1
3,2025,Aceh,Kab. Aceh Tengah,41601.58,0.00,0.0,1109.97,2.67,1109.97,2.67,0.0,1109.97,2.67,P 1
4,2025,Aceh,Kab. Aceh Barat,30802.93,0.61,0.0,22909.85,74.38,22910.46,74.38,0.0,2915.15,9.46,P 1

In [5]:
print("TPA Dataframe")
TPA.head()

TPA Dataframe

,Unnamed: 0,Tahun,P,Provinsi,Kabupaten/Kota,Nama Fasilitas,Jenis,Status,Sampahmasuk (ton/thn),Sampahmasuk Landfill (ton/thn),...,Luas Landfill Aktif (m2),Pencatatan,Jembatan Timbang,Penutupan Sampah Zona Aktif,Jml Sumur Pantau,IPL,Jml Uji Lindi,Ada Drainase,Pemanfaatan Gas Metana,Jumlah KK yang memanfaatkan gas Metana
0,NaN,2025,2,Aceh,Kab. Aceh Selatan,TPA PASIE RAJA,TPA Pemda (Non Regional),A,12775.00,12636.30,...,20,-,Ada tapi sedang rusak,-,1,"Ada, Instalasi Pengolahan Air Lindi (IPAL) di ...",-,ADA,-,-
1,NaN,2025,2,Aceh,Kab. Aceh Tenggara,TPA SELAMAT INDAH,TPA Pemda (Non Regional),A,10022.90,7796.40,...,5913.6,Kombinasi timbangan dengan Komputer (excel / t...,Ada dan berfungsi dengan baik,Sebulan sekali,4,"Ada, Instalasi Pengolahan Air Lindi (IPAL) di ...",-,ADA,Tidak ada. Gas Metana dibakar.,-
2,NaN,2025,2,Aceh,Kab. Aceh Timur,TPA Lhok Tujoh,TPA Pemda (Non Regional),A,20495.29,20312.79,...,42000,Manual Book,Tidak Ada,Tiga atau Empat Bulan Sekali,-,"Ada, Instalasi Pengolahan Air Lindi (IPAL) di ...",-,TIDAK ADA,-,-
3,NaN,2025,2,Aceh,Kab. Aceh Timur,TPA BIREM BAYEUN,TPA Pemda (Non Regional),A,9072.41,8962.91,...,15000,Manual Book,Tidak Ada,Dua minggu sekali,-,Tidak ada Instalasi Pengolahan Air Lindi (IPAL...,-,TIDAK ADA,-,-
4,NaN,2025,2,Aceh,Kab. Aceh Tengah,TPA Uwer Tetemi,TPA Pemda (Non Regional),A,23360.00,22630.00,...,2,Manual Book,Tidak Ada,Tidak ditutup sama sekali,3,"Ada, Instalasi Pengolahan Air Lindi (IPAL) di ...",-,TIDAK ADA,Tidak ada. Gas Metana dibakar.,-

In [6]:
print("MAP Dataframe")
MAP.head()

MAP Dataframe

,GID_2,GID_0,COUNTRY,GID_1,NAME_1,NL_NAME_1,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
0,IDN.1.2_1,IDN,Indonesia,IDN.1_1,Aceh,NA,AcehBarat,NA,NA,Kabupaten,Regency,1107,ID.AC.AB,"MULTIPOLYGON (((96.0691 4.1954, 96.0554 4.2052..."
1,IDN.1.1_1,IDN,Indonesia,IDN.1_1,Aceh,NA,AcehBaratDaya,NA,NA,Kabupaten,Regency,1112,ID.AC.AD,"MULTIPOLYGON (((96.942 3.5746, 96.9343 3.5782,..."
2,IDN.1.3_1,IDN,Indonesia,IDN.1_1,Aceh,NA,AcehBesar,NA,NA,Kabupaten,Regency,1108,ID.AC.AR,"MULTIPOLYGON (((95.2037 5.3128, 95.2034 5.3127..."
3,IDN.1.4_1,IDN,Indonesia,IDN.1_1,Aceh,NA,AcehJaya,NA,NA,Kabupaten,Regency,1116,ID.AC.AJ,"MULTIPOLYGON (((95.8767 4.3675, 95.8769 4.3675..."
4,IDN.1.5_1,IDN,Indonesia,IDN.1_1,Aceh,NA,AcehSelatan,NA,NA,Kabupaten,Regency,1103,ID.AC.AS,"MULTIPOLYGON (((97.7469 2.44, 97.7321 2.4227, ..."